#########################################################
# Redmine on CentOS7
#########################################################

---
- hosts: all
  roles:
    -
      role: common
      tags: [system]

- hosts: web
  roles:
    -
     role: nginx
     tags: [nginx]
    -
      role: ssl
      tags: [ssl]
    -
      role: mysql
      tags: [mysql]
    -
      role: ruby
      tags: [ruby]
    -
      role: redmine
      tags: [redmine]
    -
      role: unicorn
      tags: [unicorn]
